services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kitodo\Dlf\:
    resource: '../Classes/*'

  Kitodo\Dlf\Command\DeleteCommand:
    tags:
      - name: console.command
        command: 'kitodo:delete'

  Kitodo\Dlf\Command\HarvestCommand:
    tags:
      - name: console.command
        command: 'kitodo:harvest'

  Kitodo\Dlf\Command\IndexCommand:
    tags:
      - name: console.command
        command: 'kitodo:index'

  Kitodo\Dlf\Command\ReindexCommand:
    tags:
      - name: console.command
        command: 'kitodo:reindex'
